"""Initial consolidated schema v1

Revision ID: 0001
Revises:
Create Date: 2026-03-15

Consolidates 22 development-phase migrations into a single clean schema.
All views inlined as raw SQL (no runtime imports from app.db).
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # -- Section A: Manual ENUMs (before first create_table) --
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE backup_status AS ENUM (
                'pending', 'running', 'completed',
                'failed', 'restored'
            );
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE backup_trigger AS ENUM (
                'manual_api', 'scheduled_cron',
                'pre_restore_safety'
            );
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotation_sources",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("update_frequency", sa.Text(), nullable=True),
        sa.Column(
            "last_update",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "next_update",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_name"),
    )
    op.create_index(
        op.f("ix_annotation_sources_id"),
        "annotation_sources",
        ["id"],
        unique=False,
    )
    op.create_table(
        "cache_entries",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("cache_key", sa.Text(), nullable=False),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_accessed",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "access_count",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
        sa.Column("data_size", sa.Integer(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key", name="uq_cache_entries_cache_key"),
    )
    op.create_index(
        "idx_cache_entries_expires_at",
        "cache_entries",
        ["expires_at"],
        unique=False,
        postgresql_where="expires_at IS NOT NULL",
    )
    op.create_index(
        "idx_cache_entries_last_accessed",
        "cache_entries",
        ["last_accessed"],
        unique=False,
    )
    op.create_index(
        "idx_cache_entries_namespace",
        "cache_entries",
        ["namespace"],
        unique=False,
    )
    op.create_index(
        "idx_cache_entries_namespace_key",
        "cache_entries",
        ["namespace", "cache_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cache_entries_id"),
        "cache_entries",
        ["id"],
        unique=False,
    )
    op.create_table(
        "data_source_progress",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "idle",
                "running",
                "completed",
                "failed",
                "paused",
                name="source_status",
            ),
            nullable=False,
        ),
        sa.Column("current_page", sa.Integer(), nullable=True),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("current_item", sa.Integer(), nullable=True),
        sa.Column("total_items", sa.Integer(), nullable=True),
        sa.Column(
            "items_processed",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column("items_added", sa.Integer(), nullable=True),
        sa.Column("items_updated", sa.Integer(), nullable=True),
        sa.Column("items_failed", sa.Integer(), nullable=True),
        sa.Column(
            "progress_percentage",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "current_operation",
            sa.Text(),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "last_error_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_successful_item",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "rate_limit_remaining",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "rate_limit_reset",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "estimated_completion",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_source_progress_id"),
        "data_source_progress",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_source_progress_source_name"),
        "data_source_progress",
        ["source_name"],
        unique=True,
    )
    op.create_table(
        "gene_normalization_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("original_text", sa.String(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column(
            "approved_symbol",
            sa.String(),
            nullable=True,
        ),
        sa.Column("hgnc_id", sa.String(), nullable=True),
        sa.Column(
            "normalization_log",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "final_gene_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column("staging_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "api_calls_made",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "processing_time_ms",
            sa.Integer(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gene_normalization_log_approved_symbol"),
        "gene_normalization_log",
        ["approved_symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_log_created_at"),
        "gene_normalization_log",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_log_hgnc_id"),
        "gene_normalization_log",
        ["hgnc_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_log_id"),
        "gene_normalization_log",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_log_original_text"),
        "gene_normalization_log",
        ["original_text"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_log_source_name"),
        "gene_normalization_log",
        ["source_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_log_success"),
        "gene_normalization_log",
        ["success"],
        unique=False,
    )
    op.create_table(
        "gene_normalization_staging",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("original_text", sa.String(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column(
            "original_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "normalization_log",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reviewed_by", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column(
            "manual_approved_symbol",
            sa.String(),
            nullable=True,
        ),
        sa.Column("manual_hgnc_id", sa.String(), nullable=True),
        sa.Column(
            "manual_aliases",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "resolved_gene_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "resolution_method",
            sa.String(),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "priority_score",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "requires_expert_review",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "is_duplicate_submission",
            sa.Boolean(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gene_normalization_staging_created_at"),
        "gene_normalization_staging",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_staging_id"),
        "gene_normalization_staging",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_staging_original_text"),
        "gene_normalization_staging",
        ["original_text"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_staging_priority_score"),
        "gene_normalization_staging",
        ["priority_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_staging_source_name"),
        "gene_normalization_staging",
        ["source_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_normalization_staging_status"),
        "gene_normalization_staging",
        ["status"],
        unique=False,
    )
    op.create_table(
        "genes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "hgnc_id",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "approved_symbol",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column("aliases", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "valid_from",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "valid_to",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("'infinity'::timestamptz"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_genes_approved_symbol"),
        "genes",
        ["approved_symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genes_hgnc_id"),
        "genes",
        ["hgnc_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_genes_id"),
        "genes",
        ["id"],
        unique=False,
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_runs_id"),
        "pipeline_runs",
        ["id"],
        unique=False,
    )
    op.create_table(
        "schema_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "version",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "alembic_revision",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_index(
        op.f("ix_schema_versions_id"),
        "schema_versions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "static_sources",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "source_name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "scoring_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_by",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_name"),
    )
    op.create_index(
        op.f("ix_static_sources_id"),
        "static_sources",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_sources_is_active"),
        "static_sources",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_sources_source_type"),
        "static_sources",
        ["source_type"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "username",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "full_name",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column("permissions", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column(
            "failed_login_attempts",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column(
            "password_reset_token",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "password_reset_expires",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "email_verification_token",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_email"),
        "users",
        ["email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_users_id"),
        "users",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_is_active"),
        "users",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_role"),
        "users",
        ["role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_username"),
        "users",
        ["username"],
        unique=True,
    )
    op.create_table(
        "annotation_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("gene_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "operation",
            sa.String(length=20),
            nullable=True,
        ),
        sa.Column(
            "old_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "new_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "changed_by",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column("changed_at", sa.DateTime(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotation_history_gene_id"),
        "annotation_history",
        ["gene_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotation_history_id"),
        "annotation_history",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotation_history_source"),
        "annotation_history",
        ["source"],
        unique=False,
    )
    op.create_table(
        "backup_jobs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "filename",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "file_path",
            sa.String(length=1000),
            nullable=False,
        ),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column(
            "checksum_sha256",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "format",
            sa.String(length=20),
            nullable=True,
        ),
        sa.Column(
            "compression_level",
            sa.SmallInteger(),
            nullable=True,
        ),
        sa.Column("include_logs", sa.Boolean(), nullable=True),
        sa.Column("include_cache", sa.Boolean(), nullable=True),
        sa.Column(
            "parallel_jobs",
            sa.SmallInteger(),
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "running",
                "completed",
                "failed",
                "restored",
                name="backup_status",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "trigger_source",
            postgresql.ENUM(
                "manual_api",
                "scheduled_cron",
                "pre_restore_safety",
                name="backup_trigger",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "duration_seconds",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_by_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "error_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "database_size_bytes",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column("tables_count", sa.Integer(), nullable=True),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename"),
    )
    op.create_index(
        op.f("ix_backup_jobs_id"),
        "backup_jobs",
        ["id"],
        unique=False,
    )
    op.create_table(
        "data_releases",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "version",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "release_date",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "published_by_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column("gene_count", sa.Integer(), nullable=True),
        sa.Column(
            "total_evidence_count",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "export_file_path",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "export_checksum",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "doi",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column("citation_text", sa.Text(), nullable=True),
        sa.Column("release_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["published_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_releases_id"),
        "data_releases",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_releases_status"),
        "data_releases",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_releases_version"),
        "data_releases",
        ["version"],
        unique=True,
    )
    op.create_table(
        "gene_annotations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("gene_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "version",
            sa.String(length=20),
            nullable=True,
        ),
        sa.Column(
            "annotations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "source_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "gene_id",
            "source",
            name="unique_gene_source",
        ),
    )
    op.create_index(
        op.f("ix_gene_annotations_gene_id"),
        "gene_annotations",
        ["gene_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_annotations_id"),
        "gene_annotations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_annotations_source"),
        "gene_annotations",
        ["source"],
        unique=False,
    )
    op.create_table(
        "gene_curations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("gene_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "evidence_count",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column("source_count", sa.Integer(), nullable=True),
        sa.Column(
            "panelapp_panels",
            sa.ARRAY(sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "literature_refs",
            sa.ARRAY(sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "diagnostic_panels",
            sa.ARRAY(sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "hpo_terms",
            sa.ARRAY(sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "pubtator_pmids",
            sa.ARRAY(sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "omim_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "clinvar_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "constraint_scores",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "expression_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("evidence_score", sa.Float(), nullable=True),
        sa.Column(
            "classification",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gene_id"),
    )
    op.create_index(
        op.f("ix_gene_curations_evidence_score"),
        "gene_curations",
        ["evidence_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_curations_id"),
        "gene_curations",
        ["id"],
        unique=False,
    )
    op.create_table(
        "gene_evidence",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("gene_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "source_detail",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "evidence_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("evidence_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "gene_id",
            "source_name",
            "source_detail",
            name="gene_evidence_source_idx",
        ),
    )
    op.create_index(
        op.f("ix_gene_evidence_id"),
        "gene_evidence",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gene_evidence_source_name"),
        "gene_evidence",
        ["source_name"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "token_hash",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "family_id",
            sa.String(length=36),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"),
        "refresh_tokens",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "static_evidence_uploads",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column(
            "evidence_name",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "file_hash",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "content_type",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "upload_status",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "processing_log",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("gene_count", sa.Integer(), nullable=True),
        sa.Column(
            "genes_normalized",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column("genes_failed", sa.Integer(), nullable=True),
        sa.Column("genes_staged", sa.Integer(), nullable=True),
        sa.Column(
            "upload_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "uploaded_by",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["static_sources.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_static_evidence_uploads_file_hash"),
        "static_evidence_uploads",
        ["file_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_evidence_uploads_id"),
        "static_evidence_uploads",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_evidence_uploads_source_id"),
        "static_evidence_uploads",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_evidence_uploads_upload_status"),
        "static_evidence_uploads",
        ["upload_status"],
        unique=False,
    )
    op.create_table(
        "static_source_audit",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "action",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "changes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "performed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["static_sources.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_static_source_audit_id"),
        "static_source_audit",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_source_audit_source_id"),
        "static_source_audit",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "system_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("logger", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_logs_id"),
        "system_logs",
        ["id"],
        unique=False,
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "key",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "value_type",
            postgresql.ENUM(
                "string",
                "number",
                "boolean",
                "json",
                name="setting_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            postgresql.ENUM(
                "cache",
                "security",
                "pipeline",
                "api",
                "database",
                "backup",
                "logging",
                "features",
                name="setting_category",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "default_value",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "requires_restart",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "validation_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("is_readonly", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_by_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_settings_category"),
        "system_settings",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_settings_id"),
        "system_settings",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_settings_key"),
        "system_settings",
        ["key"],
        unique=True,
    )
    op.create_table(
        "setting_audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "setting_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "setting_key",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "old_value",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "new_value",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "changed_by_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
        ),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["setting_id"],
            ["system_settings.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # -- Section B: Special indexes not captured by autogenerate --
    op.execute("CREATE INDEX idx_gene_symbol_upper ON genes (UPPER(approved_symbol))")
    op.execute(
        "CREATE INDEX idx_genes_valid_time ON genes USING GIST (tstzrange(valid_from, valid_to))"
    )
    op.execute(
        "CREATE INDEX idx_gene_evidence_source_detail "
        "ON gene_evidence "
        "(source_name, source_detail) "
        "WHERE source_name IN "
        "('DiagnosticPanels', 'Literature')"
    )
    op.execute(
        "CREATE INDEX idx_gene_evidence_providers_gin "
        "ON gene_evidence "
        "USING GIN ((evidence_data->'providers')) "
        "WHERE source_name = 'DiagnosticPanels'"
    )
    op.execute(
        "CREATE INDEX "
        "idx_gene_evidence_publications_gin "
        "ON gene_evidence "
        "USING GIN ((evidence_data->'publications')) "
        "WHERE source_name = 'Literature'"
    )

    # -- Section C: Views (23 in dependency order) --

    # 1. cache_stats (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW cache_stats AS
        SELECT cache_entries.namespace,
            count(*) AS total_entries,
            sum(COALESCE(
                cache_entries.data_size,
                pg_column_size(cache_entries.data)
            )) AS total_size_bytes,
            sum(cache_entries.access_count)
                AS total_accesses,
            avg(cache_entries.access_count)
                AS avg_accesses,
            count(*) FILTER (
                WHERE cache_entries.expires_at IS NULL
                OR cache_entries.expires_at > now()
            ) AS active_entries,
            count(*) FILTER (
                WHERE cache_entries.expires_at
                    IS NOT NULL
                AND cache_entries.expires_at <= now()
            ) AS expired_entries,
            max(cache_entries.last_accessed)
                AS last_access_time,
            min(cache_entries.created_at)
                AS oldest_entry,
            max(cache_entries.created_at)
                AS newest_entry
        FROM cache_entries
        GROUP BY cache_entries.namespace
    """)

    # 2. evidence_source_counts (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW evidence_source_counts AS
        SELECT ge.id AS evidence_id,
            ge.gene_id,
            g.approved_symbol,
            ge.source_name,
            CASE ge.source_name
                WHEN 'PanelApp'::text THEN
                    (COALESCE(jsonb_array_length(
                        ge.evidence_data
                            -> 'panels'::text
                    ), 0))::bigint
                WHEN 'HPO'::text THEN
                    ((COALESCE(jsonb_array_length(
                        ge.evidence_data
                            -> 'hpo_terms'::text
                    ), 0)
                    + COALESCE(jsonb_array_length(
                        ge.evidence_data
                            -> 'diseases'::text
                    ), 0)))::bigint
                WHEN 'PubTator'::text THEN
                    (COALESCE(
                        (ge.evidence_data
                            ->> 'publication_count'
                                ::text)::integer,
                        jsonb_array_length(
                            ge.evidence_data
                                -> 'pmids'::text
                        )
                    ))::bigint
                WHEN 'DiagnosticPanels'::text THEN
                    (COALESCE(
                        (ge.evidence_data
                            ->> 'panel_count'
                                ::text)::integer,
                        jsonb_array_length(
                            ge.evidence_data
                                -> 'panels'::text
                        )
                    ))::bigint
                WHEN 'GenCC'::text THEN
                    (COALESCE(jsonb_array_length(
                        ge.evidence_data
                            -> 'classifications'::text
                    ), 0))::bigint
                WHEN 'ClinGen'::text THEN
                    (COALESCE(
                        (ge.evidence_data
                            ->> 'assertion_count'
                                ::text)::integer,
                        1
                    ))::bigint
                WHEN 'Literature'::text THEN
                    (COALESCE(
                        (ge.evidence_data
                            ->> 'publication_count'
                                ::text)::integer,
                        jsonb_array_length(
                            ge.evidence_data
                                -> 'publications'::text
                        )
                    ))::bigint
                ELSE (0)::bigint
            END AS source_count
        FROM gene_evidence ge
        JOIN genes g ON ge.gene_id = g.id
    """)

    # 3. evidence_classification_weights (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW evidence_classification_weights AS
        WITH gencc_weighted AS (
            SELECT ge.id AS evidence_id,
                g.id AS gene_id,
                g.approved_symbol,
                ge.source_name,
                COALESCE(
                    (SELECT MAX(
                        CASE lower(
                            replace(
                                elem.value::text,
                                '"', ''
                            ))
                            WHEN 'definitive' THEN 1.0
                            WHEN 'strong' THEN 0.8
                            WHEN 'moderate' THEN 0.6
                            WHEN 'supportive' THEN 0.5
                            WHEN 'limited' THEN 0.4
                            WHEN 'disputed evidence'
                                THEN 0.2
                            WHEN 'no known disease relationship'
                                THEN 0.0
                            ELSE 0.0
                        END
                    ) FROM jsonb_array_elements(
                        ge.evidence_data
                            -> 'classifications'
                    ) elem),
                    0.0
                ) AS classification_weight
            FROM gene_evidence ge
            JOIN genes g ON ge.gene_id = g.id
            WHERE ge.source_name::text = 'GenCC'::text
        ), clingen_weights AS (
            SELECT ge.id AS evidence_id,
                g.id AS gene_id,
                g.approved_symbol,
                ge.source_name,
                CASE
                    WHEN jsonb_typeof(
                        ge.evidence_data
                            -> 'classifications'::text
                    ) = 'array'::text THEN
                        CASE (ge.evidence_data
                            -> 'classifications'::text
                        ) ->> 0
                            WHEN 'Definitive'::text
                                THEN 1.0
                            WHEN 'Strong'::text
                                THEN 0.8
                            WHEN 'Moderate'::text
                                THEN 0.6
                            WHEN 'Limited'::text
                                THEN 0.4
                            WHEN 'Disputed'::text
                                THEN 0.2
                            WHEN 'No Known Disease Relationship'::text
                                THEN 0.0
                            WHEN 'No Known Disease Relationship*'::text
                                THEN 0.0
                            ELSE 0.0
                        END
                    WHEN (ge.evidence_data
                        ->> 'classification'::text
                    ) IS NOT NULL THEN
                        CASE ge.evidence_data
                            ->> 'classification'::text
                            WHEN 'Definitive'::text
                                THEN 1.0
                            WHEN 'Strong'::text
                                THEN 0.8
                            WHEN 'Moderate'::text
                                THEN 0.6
                            WHEN 'Limited'::text
                                THEN 0.4
                            WHEN 'Disputed'::text
                                THEN 0.2
                            WHEN 'No Known Disease Relationship'::text
                                THEN 0.0
                            WHEN 'No Known Disease Relationship*'::text
                                THEN 0.0
                            ELSE 0.0
                        END
                    ELSE 0.0
                END AS classification_weight
            FROM gene_evidence ge
            JOIN genes g ON ge.gene_id = g.id
            WHERE ge.source_name::text
                = 'ClinGen'::text
        )
        SELECT clingen_weights.evidence_id,
            clingen_weights.gene_id,
            clingen_weights.approved_symbol,
            clingen_weights.source_name,
            clingen_weights.classification_weight
        FROM clingen_weights
        UNION ALL
        SELECT gencc_weighted.evidence_id,
            gencc_weighted.gene_id,
            gencc_weighted.approved_symbol,
            gencc_weighted.source_name,
            gencc_weighted.classification_weight
        FROM gencc_weighted
    """)

    # 4. string_ppi_percentiles (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW string_ppi_percentiles AS
        SELECT
            ga.gene_id,
            g.approved_symbol,
            CAST(
                ga.annotations->'ppi_score' AS FLOAT
            ) as ppi_score,
            PERCENT_RANK() OVER (
                ORDER BY CAST(
                    ga.annotations->'ppi_score'
                    AS FLOAT
                )
            ) AS percentile_rank
        FROM gene_annotations ga
        JOIN genes g ON g.id = ga.gene_id
        WHERE ga.annotations ? 'ppi_score'
          AND ga.annotations->>'ppi_score'
              IS NOT NULL
          AND ga.annotations->>'ppi_score' != 'null'
          AND CAST(
              ga.annotations->>'ppi_score' AS FLOAT
          ) > 0
    """)

    # 5. admin_logs_filtered (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW admin_logs_filtered AS
        SELECT
            sl.id::bigint,
            sl.timestamp::timestamptz,
            sl.level::text,
            sl.logger::text,
            sl.message::text,
            sl.request_id::text,
            sl.user_id::bigint,
            u.email::text AS user_email,
            sl.ip_address::text,
            sl.user_agent::text,
            sl.path::text,
            sl.method::text,
            sl.status_code::integer,
            sl.duration_ms::float8,
            sl.error_type::text,
            sl.context->>'action' AS action,
            sl.context->>'endpoint' AS endpoint,
            CASE
                WHEN sl.status_code < 400
                    THEN 'success'
                WHEN sl.status_code < 500
                    THEN 'client_error'
                ELSE 'server_error'
            END::text AS status_category,
            DATE(sl.timestamp) AS log_date,
            EXTRACT(HOUR FROM sl.timestamp)::integer
                AS log_hour
        FROM system_logs sl
        LEFT JOIN users u ON sl.user_id = u.id
        WHERE sl.path IS NOT NULL
    """)

    # 6. datasource_metadata_panelapp (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW datasource_metadata_panelapp AS
        SELECT
            ge.gene_id::bigint,
            g.approved_symbol::text
                AS gene_symbol,
            ge.evidence_data->>'source'::text
                AS source_region,
            jsonb_array_length(
                COALESCE(
                    ge.evidence_data->'panels',
                    '[]'::jsonb
                )
            )::integer AS panel_count,
            ge.evidence_data->'panels' AS panels,
            COALESCE(
                (ge.evidence_data
                    ->>'confidence_level')::float,
                0.0
            )::float8 AS max_confidence,
            ge.evidence_data->>'moi'::text
                AS mode_of_inheritance,
            ge.created_at::timestamptz,
            ge.updated_at::timestamptz
        FROM gene_evidence ge
        JOIN genes g ON g.id = ge.gene_id
        WHERE ge.source_name = 'PanelApp'
    """)

    # 7. datasource_metadata_gencc (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW datasource_metadata_gencc AS
        SELECT
            ge.gene_id::bigint,
            g.approved_symbol::text
                AS gene_symbol,
            jsonb_array_length(
                COALESCE(
                    ge.evidence_data
                        ->'classifications',
                    '[]'::jsonb
                )
            )::integer AS classification_count,
            ge.evidence_data->'classifications'
                AS classifications,
            ge.evidence_data->>'disease_id'::text
                AS disease_id,
            ge.evidence_data->>'disease_title'::text
                AS disease_title,
            ge.created_at::timestamptz,
            ge.updated_at::timestamptz
        FROM gene_evidence ge
        JOIN genes g ON g.id = ge.gene_id
        WHERE ge.source_name = 'GenCC'
    """)

    # 8. v_diagnostic_panel_providers (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW v_diagnostic_panel_providers AS
        SELECT
            jsonb_array_elements_text(
                evidence_data->'providers'
            ) as provider_name,
            COUNT(DISTINCT gene_id) as gene_count,
            MAX(updated_at) as last_updated
        FROM gene_evidence
        WHERE source_name = 'DiagnosticPanels'
        GROUP BY provider_name
        ORDER BY gene_count DESC
    """)

    # 9. v_literature_publications (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW v_literature_publications AS
        SELECT
            jsonb_array_elements_text(
                evidence_data->'publications'
            ) as pmid,
            COUNT(DISTINCT gene_id) as gene_count,
            MAX(updated_at) as last_updated
        FROM gene_evidence
        WHERE source_name = 'Literature'
        GROUP BY pmid
        ORDER BY gene_count DESC
    """)

    # 10. source_distribution_hpo (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW source_distribution_hpo AS
        SELECT
            jsonb_array_length(
                evidence_data->'hpo_terms'
            ) as hpo_term_count,
            COUNT(*) as gene_count
        FROM gene_evidence
        WHERE source_name = 'HPO'
            AND evidence_data->'hpo_terms'
                IS NOT NULL
        GROUP BY 1
        ORDER BY 1 DESC
    """)

    # 11. source_distribution_gencc (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW source_distribution_gencc AS
        SELECT
            jsonb_array_elements_text(
                evidence_data->'classifications'
            ) as classification,
            COUNT(DISTINCT gene_id) as gene_count
        FROM gene_evidence
        WHERE source_name = 'GenCC'
            AND evidence_data->'classifications'
                IS NOT NULL
        GROUP BY 1
        ORDER BY 2 DESC
    """)

    # 12. source_distribution_clingen (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW source_distribution_clingen AS
        SELECT
            jsonb_array_elements_text(
                evidence_data->'classifications'
            ) as classification,
            COUNT(DISTINCT gene_id) as gene_count
        FROM gene_evidence
        WHERE source_name = 'ClinGen'
            AND evidence_data->'classifications'
                IS NOT NULL
        GROUP BY 1
        ORDER BY 2 DESC
    """)

    # 13. source_distribution_diagnosticpanels (VIEW)
    op.execute("""
        CREATE VIEW
            source_distribution_diagnosticpanels AS
        SELECT
            jsonb_array_elements_text(
                evidence_data->'providers'
            ) as provider,
            COUNT(DISTINCT gene_id) as gene_count
        FROM gene_evidence
        WHERE source_name = 'DiagnosticPanels'
            AND evidence_data->'providers'
                IS NOT NULL
        GROUP BY 1
        ORDER BY 2 DESC
    """)

    # 14. source_distribution_panelapp (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW source_distribution_panelapp AS
        SELECT
            jsonb_array_elements_text(
                evidence_data->'evidence_levels'
            ) as evidence_level,
            COUNT(DISTINCT gene_id) as gene_count
        FROM gene_evidence
        WHERE source_name = 'PanelApp'
            AND evidence_data->'evidence_levels'
                IS NOT NULL
        GROUP BY 1
        ORDER BY 1 DESC
    """)

    # 15. source_distribution_pubtator (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW source_distribution_pubtator AS
        SELECT
            CAST(
                evidence_data->>'publication_count'
                AS INTEGER
            ) as publication_count,
            COUNT(DISTINCT gene_id) as gene_count
        FROM gene_evidence
        WHERE source_name = 'PubTator'
            AND evidence_data->>'publication_count'
                IS NOT NULL
        GROUP BY 1
        ORDER BY 1 DESC
        LIMIT 20
    """)

    # 16. gene_hpo_classifications (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW gene_hpo_classifications AS
        SELECT
            g.id AS gene_id,
            g.approved_symbol AS gene_symbol,
            ga.annotations
                ->'classification'
                ->'clinical_group'
                ->>'primary'
                AS clinical_group,
            ga.annotations
                ->'classification'
                ->'onset_group'
                ->>'primary'
                AS onset_group,
            COALESCE(
                (ga.annotations
                    ->'classification'
                    ->'syndromic_assessment'
                    ->>'is_syndromic')::boolean,
                FALSE
            ) AS is_syndromic
        FROM genes g
        LEFT JOIN gene_annotations ga
            ON g.id = ga.gene_id
            AND ga.source = 'hpo'
    """)

    # 17. genes_current (VIEW) - Tier 1
    op.execute("""
        CREATE VIEW genes_current AS
        SELECT *
        FROM genes
        WHERE valid_to = 'infinity'::timestamptz
    """)

    # 18. evidence_count_percentiles (VIEW) - Tier 2
    op.execute("""
        CREATE VIEW evidence_count_percentiles AS
        SELECT
            evidence_source_counts.evidence_id,
            evidence_source_counts.gene_id,
            evidence_source_counts.approved_symbol,
            evidence_source_counts.source_name,
            evidence_source_counts.source_count,
            percent_rank() OVER (
                PARTITION BY
                    evidence_source_counts.source_name
                ORDER BY LN(
                    1.0
                    + evidence_source_counts
                        .source_count
                )
            ) AS percentile_score
        FROM evidence_source_counts
        WHERE evidence_source_counts.source_count > 0
    """)

    # 19. evidence_normalized_scores (VIEW) - Tier 2
    op.execute("""
        CREATE VIEW evidence_normalized_scores AS
        SELECT
            evidence_count_percentiles.evidence_id,
            evidence_count_percentiles.gene_id,
            evidence_count_percentiles
                .approved_symbol,
            evidence_count_percentiles.source_name,
            evidence_count_percentiles
                .percentile_score
                AS normalized_score
        FROM evidence_count_percentiles
        WHERE evidence_count_percentiles.source_name
            NOT IN ('ClinGen', 'GenCC')
        UNION ALL
        SELECT
            evidence_classification_weights
                .evidence_id,
            evidence_classification_weights.gene_id,
            evidence_classification_weights
                .approved_symbol,
            evidence_classification_weights
                .source_name,
            evidence_classification_weights
                .classification_weight
                AS normalized_score
        FROM evidence_classification_weights
        WHERE evidence_classification_weights
            .source_name::text = 'ClinGen'::text
        UNION ALL
        SELECT
            evidence_classification_weights
                .evidence_id,
            evidence_classification_weights.gene_id,
            evidence_classification_weights
                .approved_symbol,
            evidence_classification_weights
                .source_name,
            evidence_classification_weights
                .classification_weight
                AS normalized_score
        FROM evidence_classification_weights
        WHERE evidence_classification_weights
            .source_name::text = 'GenCC'::text
    """)

    # 20. combined_evidence_scores (VIEW) - Tier 3
    op.execute("""
        CREATE VIEW combined_evidence_scores AS
        SELECT
            evidence_normalized_scores.evidence_id,
            evidence_normalized_scores.gene_id,
            evidence_normalized_scores
                .approved_symbol,
            evidence_normalized_scores.source_name,
            evidence_normalized_scores.source_name
                AS display_name,
            evidence_normalized_scores
                .normalized_score,
            'pipeline'::text AS source_type
        FROM evidence_normalized_scores
    """)

    # 21. evidence_summary_view (VIEW) - Tier 3
    op.execute("""
        CREATE VIEW evidence_summary_view AS
        SELECT ge.id,
            ge.gene_id,
            g.approved_symbol,
            g.hgnc_id,
            ge.source_name,
            ge.evidence_data,
            COALESCE(
                ces.normalized_score,
                0::double precision
            ) AS normalized_score,
            gc.classification,
            gc.updated_at AS last_curated
        FROM gene_evidence ge
        JOIN genes g ON ge.gene_id = g.id
        LEFT JOIN combined_evidence_scores ces
            ON ge.id = ces.evidence_id
        LEFT JOIN gene_curations gc
            ON g.id = gc.gene_id
    """)

    # 22. gene_scores (MATERIALIZED VIEW) - Tier 4
    op.execute("""
        CREATE MATERIALIZED VIEW gene_scores AS
        WITH source_scores_per_gene AS (
            SELECT g.id AS gene_id,
                   g.approved_symbol,
                   g.hgnc_id,
                   ces.source_name,
                   MAX(ces.normalized_score)
                       AS source_score
            FROM genes g
            INNER JOIN combined_evidence_scores ces
                ON g.id = ces.gene_id
            GROUP BY g.id, g.approved_symbol,
                     g.hgnc_id, ces.source_name
        )
        SELECT gene_id,
               approved_symbol,
               hgnc_id,
               COUNT(DISTINCT source_name)
                   AS source_count,
               COUNT(DISTINCT source_name)
                   AS evidence_count,
               SUM(source_score) AS raw_score,
               SUM(source_score) /
                   (SELECT COUNT(DISTINCT source_name)
                    FROM combined_evidence_scores)
                   * 100 AS percentage_score,
               jsonb_object_agg(
                   source_name,
                   ROUND(source_score::numeric, 4)
               ) AS source_scores,
               (SELECT COUNT(DISTINCT source_name)
                FROM combined_evidence_scores)
                   AS total_active_sources,
               CASE
                   WHEN COUNT(DISTINCT source_name)
                       >= 4
                       AND SUM(source_score) /
                       (SELECT COUNT(
                           DISTINCT source_name)
                        FROM combined_evidence_scores)
                       * 100 >= 50
                       THEN 'comprehensive_support'
                   WHEN COUNT(DISTINCT source_name)
                       >= 3
                       AND SUM(source_score) /
                       (SELECT COUNT(
                           DISTINCT source_name)
                        FROM combined_evidence_scores)
                       * 100 >= 35
                       THEN 'multi_source_support'
                   WHEN COUNT(DISTINCT source_name)
                       >= 2
                       AND SUM(source_score) /
                       (SELECT COUNT(
                           DISTINCT source_name)
                        FROM combined_evidence_scores)
                       * 100 >= 20
                       THEN 'established_support'
                   WHEN SUM(source_score) /
                       (SELECT COUNT(
                           DISTINCT source_name)
                        FROM combined_evidence_scores)
                       * 100 >= 10
                       THEN 'preliminary_evidence'
                   WHEN SUM(source_score) /
                       (SELECT COUNT(
                           DISTINCT source_name)
                        FROM combined_evidence_scores)
                       * 100 > 0
                       THEN 'minimal_evidence'
                   ELSE 'no_evidence'
               END AS evidence_tier,
               CASE
                   WHEN COUNT(DISTINCT source_name)
                       >= 2
                       AND SUM(source_score) /
                       (SELECT COUNT(
                           DISTINCT source_name)
                        FROM combined_evidence_scores)
                       * 100 >= 20
                       THEN 'well_supported'
                   WHEN SUM(source_score) /
                       (SELECT COUNT(
                           DISTINCT source_name)
                        FROM combined_evidence_scores)
                       * 100 > 0
                       THEN 'emerging_evidence'
                   ELSE 'insufficient'
               END AS evidence_group
        FROM source_scores_per_gene
        GROUP BY gene_id, approved_symbol, hgnc_id
    """)
    op.execute("CREATE UNIQUE INDEX idx_gene_scores_gene_id ON gene_scores (gene_id)")
    op.execute("CREATE INDEX idx_gene_scores_percentage_score ON gene_scores (percentage_score)")
    op.execute("CREATE INDEX idx_gene_scores_evidence_tier ON gene_scores (evidence_tier)")
    op.execute("REFRESH MATERIALIZED VIEW gene_scores")

    # 23. gene_list_detailed (VIEW) - Tier 5
    op.execute("""
        CREATE VIEW gene_list_detailed AS
        SELECT
            g.id::bigint AS gene_id,
            g.hgnc_id::text AS hgnc_id,
            g.approved_symbol::text AS gene_symbol,
            g.aliases::text[] AS alias_symbols,
            COALESCE(gs.raw_score, 0.0)::float8
                AS total_score,
            COALESCE(
                gs.percentage_score, 0.0
            )::float8 AS percentage_score,
            CASE
                WHEN gs.percentage_score >= 80
                    THEN 'High'
                WHEN gs.percentage_score >= 50
                    THEN 'Medium'
                WHEN gs.percentage_score >= 20
                    THEN 'Low'
                ELSE 'Unknown'
            END::text AS classification,
            COALESCE(
                gs.source_count, 0
            )::integer AS source_count,
            COALESCE(
                (SELECT array_agg(
                    DISTINCT source_name
                    ORDER BY source_name
                )
                 FROM gene_evidence
                 WHERE gene_id = g.id),
                '{}'::text[]
            )::text[] AS sources,
            COALESCE(
                (SELECT COUNT(
                    DISTINCT source
                )::integer
                 FROM gene_annotations
                 WHERE gene_id = g.id),
                0
            )::integer AS annotation_count,
            COALESCE(
                (SELECT array_agg(
                    DISTINCT source
                    ORDER BY source
                )
                 FROM gene_annotations
                 WHERE gene_id = g.id),
                '{}'::text[]
            )::text[] AS annotation_sources,
            g.created_at::timestamptz
                AS created_at,
            g.updated_at::timestamptz
                AS updated_at
        FROM genes g
        LEFT JOIN gene_scores gs
            ON g.id = gs.gene_id
    """)

    # -- Section D: Seed data --

    # 14 system_settings rows
    system_settings_table = sa.table(
        "system_settings",
        sa.column("key", sa.String),
        sa.column("value", postgresql.JSONB),
        sa.column("value_type", sa.String),
        sa.column("category", sa.String),
        sa.column("description", sa.Text),
        sa.column("default_value", postgresql.JSONB),
        sa.column("requires_restart", sa.Boolean),
        sa.column("is_sensitive", sa.Boolean),
        sa.column("is_readonly", sa.Boolean),
    )
    op.bulk_insert(
        system_settings_table,
        [
            {
                "key": "cache.default_ttl",
                "value": 3600,
                "value_type": "number",
                "category": "cache",
                "description": ("Default cache TTL in seconds"),
                "default_value": 3600,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": "cache.max_memory_size",
                "value": 1000,
                "value_type": "number",
                "category": "cache",
                "description": ("Maximum L1 cache entries"),
                "default_value": 1000,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": "cache.cleanup_interval",
                "value": 3600,
                "value_type": "number",
                "category": "cache",
                "description": ("Cache cleanup interval in seconds"),
                "default_value": 3600,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": "security.jwt_expire_minutes",
                "value": 30,
                "value_type": "number",
                "category": "security",
                "description": ("JWT token expiration in minutes"),
                "default_value": 30,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": "security.max_login_attempts",
                "value": 5,
                "value_type": "number",
                "category": "security",
                "description": ("Max failed login attempts before lockout"),
                "default_value": 5,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": ("security.account_lockout_minutes"),
                "value": 15,
                "value_type": "number",
                "category": "security",
                "description": ("Account lockout duration in minutes"),
                "default_value": 15,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": "security.jwt_secret_key",
                "value": "***PLACEHOLDER***",
                "value_type": "string",
                "category": "security",
                "description": ("JWT signing secret key"),
                "default_value": "***PLACEHOLDER***",
                "requires_restart": False,
                "is_sensitive": True,
                "is_readonly": False,
            },
            {
                "key": "pipeline.hgnc_batch_size",
                "value": 50,
                "value_type": "number",
                "category": "pipeline",
                "description": "HGNC API batch size",
                "default_value": 50,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": ("pipeline.hgnc_retry_attempts"),
                "value": 3,
                "value_type": "number",
                "category": "pipeline",
                "description": ("HGNC API retry attempts"),
                "default_value": 3,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": ("pipeline.hgnc_cache_enabled"),
                "value": True,
                "value_type": "boolean",
                "category": "pipeline",
                "description": ("Enable HGNC response caching"),
                "default_value": True,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": "backup.retention_days",
                "value": 7,
                "value_type": "number",
                "category": "backup",
                "description": ("Backup retention period in days"),
                "default_value": 7,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": "backup.compression_level",
                "value": 6,
                "value_type": "number",
                "category": "backup",
                "description": ("pg_dump compression level (0-9)"),
                "default_value": 6,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": ("features.auto_update_enabled"),
                "value": True,
                "value_type": "boolean",
                "category": "features",
                "description": ("Enable automatic source updates"),
                "default_value": True,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
            {
                "key": "logging.log_retention_days",
                "value": 30,
                "value_type": "number",
                "category": "logging",
                "description": ("Days to retain system logs before cleanup"),
                "default_value": 30,
                "requires_restart": False,
                "is_sensitive": False,
                "is_readonly": False,
            },
        ],
    )

    # 2 static_sources rows
    op.execute("""
        INSERT INTO static_sources
            (source_type, source_name, display_name,
             description, scoring_metadata,
             is_active, created_by)
        VALUES
            ('hybrid', 'DiagnosticPanels',
             'Diagnostic Panels',
             'Commercial diagnostic panel evidence'
             ' from providers',
             '{"type": "count_based",'
             ' "weight": 1.0}'::jsonb,
             true, 'system'),
            ('hybrid', 'Literature',
             'Literature Evidence',
             'Manually curated literature evidence',
             '{"type": "count_based",'
             ' "weight": 1.0}'::jsonb,
             true, 'system')
        ON CONFLICT (source_name) DO NOTHING
    """)

    # 1 schema_versions row
    op.execute("""
        INSERT INTO schema_versions
            (version, alembic_revision, description)
        VALUES (
            '0.1.0', '0001',
            'Initial consolidated schema'
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # -- Drop views in reverse dependency order --
    op.execute("DROP VIEW IF EXISTS gene_list_detailed CASCADE")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS gene_scores CASCADE")
    op.execute("DROP VIEW IF EXISTS evidence_summary_view CASCADE")
    op.execute("DROP VIEW IF EXISTS combined_evidence_scores CASCADE")
    op.execute("DROP VIEW IF EXISTS evidence_normalized_scores CASCADE")
    op.execute("DROP VIEW IF EXISTS evidence_count_percentiles CASCADE")
    op.execute("DROP VIEW IF EXISTS genes_current CASCADE")
    op.execute("DROP VIEW IF EXISTS gene_hpo_classifications CASCADE")
    op.execute("DROP VIEW IF EXISTS source_distribution_pubtator CASCADE")
    op.execute("DROP VIEW IF EXISTS source_distribution_panelapp CASCADE")
    op.execute("DROP VIEW IF EXISTS source_distribution_diagnosticpanels CASCADE")
    op.execute("DROP VIEW IF EXISTS source_distribution_clingen CASCADE")
    op.execute("DROP VIEW IF EXISTS source_distribution_gencc CASCADE")
    op.execute("DROP VIEW IF EXISTS source_distribution_hpo CASCADE")
    op.execute("DROP VIEW IF EXISTS v_literature_publications CASCADE")
    op.execute("DROP VIEW IF EXISTS v_diagnostic_panel_providers CASCADE")
    op.execute("DROP VIEW IF EXISTS datasource_metadata_gencc CASCADE")
    op.execute("DROP VIEW IF EXISTS datasource_metadata_panelapp CASCADE")
    op.execute("DROP VIEW IF EXISTS admin_logs_filtered CASCADE")
    op.execute("DROP VIEW IF EXISTS string_ppi_percentiles CASCADE")
    op.execute("DROP VIEW IF EXISTS evidence_classification_weights CASCADE")
    op.execute("DROP VIEW IF EXISTS evidence_source_counts CASCADE")
    op.execute("DROP VIEW IF EXISTS cache_stats CASCADE")

    # -- Drop special indexes --
    op.execute("DROP INDEX IF EXISTS idx_gene_symbol_upper")
    op.execute("DROP INDEX IF EXISTS idx_genes_valid_time")
    op.execute("DROP INDEX IF EXISTS idx_gene_evidence_source_detail")
    op.execute("DROP INDEX IF EXISTS idx_gene_evidence_providers_gin")
    op.execute("DROP INDEX IF EXISTS idx_gene_evidence_publications_gin")

    # -- Drop all 22 tables (reverse order) --
    op.drop_table("setting_audit_log")
    op.drop_index(
        op.f("ix_system_settings_key"),
        table_name="system_settings",
    )
    op.drop_index(
        op.f("ix_system_settings_id"),
        table_name="system_settings",
    )
    op.drop_index(
        op.f("ix_system_settings_category"),
        table_name="system_settings",
    )
    op.drop_table("system_settings")
    op.drop_index(
        op.f("ix_system_logs_id"),
        table_name="system_logs",
    )
    op.drop_table("system_logs")
    op.drop_index(
        op.f("ix_static_source_audit_source_id"),
        table_name="static_source_audit",
    )
    op.drop_index(
        op.f("ix_static_source_audit_id"),
        table_name="static_source_audit",
    )
    op.drop_table("static_source_audit")
    op.drop_index(
        op.f("ix_static_evidence_uploads_upload_status"),
        table_name="static_evidence_uploads",
    )
    op.drop_index(
        op.f("ix_static_evidence_uploads_source_id"),
        table_name="static_evidence_uploads",
    )
    op.drop_index(
        op.f("ix_static_evidence_uploads_id"),
        table_name="static_evidence_uploads",
    )
    op.drop_index(
        op.f("ix_static_evidence_uploads_file_hash"),
        table_name="static_evidence_uploads",
    )
    op.drop_table("static_evidence_uploads")
    op.drop_index(
        op.f("ix_refresh_tokens_token_hash"),
        table_name="refresh_tokens",
    )
    op.drop_index(
        op.f("ix_refresh_tokens_family_id"),
        table_name="refresh_tokens",
    )
    op.drop_table("refresh_tokens")
    op.drop_index(
        op.f("ix_gene_evidence_source_name"),
        table_name="gene_evidence",
    )
    op.drop_index(
        op.f("ix_gene_evidence_id"),
        table_name="gene_evidence",
    )
    op.drop_table("gene_evidence")
    op.drop_index(
        op.f("ix_gene_curations_id"),
        table_name="gene_curations",
    )
    op.drop_index(
        op.f("ix_gene_curations_evidence_score"),
        table_name="gene_curations",
    )
    op.drop_table("gene_curations")
    op.drop_index(
        op.f("ix_gene_annotations_source"),
        table_name="gene_annotations",
    )
    op.drop_index(
        op.f("ix_gene_annotations_id"),
        table_name="gene_annotations",
    )
    op.drop_index(
        op.f("ix_gene_annotations_gene_id"),
        table_name="gene_annotations",
    )
    op.drop_table("gene_annotations")
    op.drop_index(
        op.f("ix_data_releases_version"),
        table_name="data_releases",
    )
    op.drop_index(
        op.f("ix_data_releases_status"),
        table_name="data_releases",
    )
    op.drop_index(
        op.f("ix_data_releases_id"),
        table_name="data_releases",
    )
    op.drop_table("data_releases")
    op.drop_index(
        op.f("ix_backup_jobs_id"),
        table_name="backup_jobs",
    )
    op.drop_table("backup_jobs")
    op.drop_index(
        op.f("ix_annotation_history_source"),
        table_name="annotation_history",
    )
    op.drop_index(
        op.f("ix_annotation_history_id"),
        table_name="annotation_history",
    )
    op.drop_index(
        op.f("ix_annotation_history_gene_id"),
        table_name="annotation_history",
    )
    op.drop_table("annotation_history")
    op.drop_index(
        op.f("ix_users_username"),
        table_name="users",
    )
    op.drop_index(
        op.f("ix_users_role"),
        table_name="users",
    )
    op.drop_index(
        op.f("ix_users_is_active"),
        table_name="users",
    )
    op.drop_index(
        op.f("ix_users_id"),
        table_name="users",
    )
    op.drop_index(
        op.f("ix_users_email"),
        table_name="users",
    )
    op.drop_table("users")
    op.drop_index(
        op.f("ix_static_sources_source_type"),
        table_name="static_sources",
    )
    op.drop_index(
        op.f("ix_static_sources_is_active"),
        table_name="static_sources",
    )
    op.drop_index(
        op.f("ix_static_sources_id"),
        table_name="static_sources",
    )
    op.drop_table("static_sources")
    op.drop_index(
        op.f("ix_schema_versions_id"),
        table_name="schema_versions",
    )
    op.drop_table("schema_versions")
    op.drop_index(
        op.f("ix_pipeline_runs_id"),
        table_name="pipeline_runs",
    )
    op.drop_table("pipeline_runs")
    op.drop_index(
        op.f("ix_genes_id"),
        table_name="genes",
    )
    op.drop_index(
        op.f("ix_genes_hgnc_id"),
        table_name="genes",
    )
    op.drop_index(
        op.f("ix_genes_approved_symbol"),
        table_name="genes",
    )
    op.drop_table("genes")
    op.drop_index(
        op.f("ix_gene_normalization_staging_status"),
        table_name="gene_normalization_staging",
    )
    op.drop_index(
        op.f("ix_gene_normalization_staging_source_name"),
        table_name="gene_normalization_staging",
    )
    op.drop_index(
        op.f("ix_gene_normalization_staging_priority_score"),
        table_name="gene_normalization_staging",
    )
    op.drop_index(
        op.f("ix_gene_normalization_staging_original_text"),
        table_name="gene_normalization_staging",
    )
    op.drop_index(
        op.f("ix_gene_normalization_staging_id"),
        table_name="gene_normalization_staging",
    )
    op.drop_index(
        op.f("ix_gene_normalization_staging_created_at"),
        table_name="gene_normalization_staging",
    )
    op.drop_table("gene_normalization_staging")
    op.drop_index(
        op.f("ix_gene_normalization_log_success"),
        table_name="gene_normalization_log",
    )
    op.drop_index(
        op.f("ix_gene_normalization_log_source_name"),
        table_name="gene_normalization_log",
    )
    op.drop_index(
        op.f("ix_gene_normalization_log_original_text"),
        table_name="gene_normalization_log",
    )
    op.drop_index(
        op.f("ix_gene_normalization_log_id"),
        table_name="gene_normalization_log",
    )
    op.drop_index(
        op.f("ix_gene_normalization_log_hgnc_id"),
        table_name="gene_normalization_log",
    )
    op.drop_index(
        op.f("ix_gene_normalization_log_created_at"),
        table_name="gene_normalization_log",
    )
    op.drop_index(
        op.f("ix_gene_normalization_log_approved_symbol"),
        table_name="gene_normalization_log",
    )
    op.drop_table("gene_normalization_log")
    op.drop_index(
        op.f("ix_data_source_progress_source_name"),
        table_name="data_source_progress",
    )
    op.drop_index(
        op.f("ix_data_source_progress_id"),
        table_name="data_source_progress",
    )
    op.drop_table("data_source_progress")
    op.drop_index(
        op.f("ix_cache_entries_id"),
        table_name="cache_entries",
    )
    op.drop_index(
        "idx_cache_entries_namespace_key",
        table_name="cache_entries",
    )
    op.drop_index(
        "idx_cache_entries_namespace",
        table_name="cache_entries",
    )
    op.drop_index(
        "idx_cache_entries_last_accessed",
        table_name="cache_entries",
    )
    op.drop_index(
        "idx_cache_entries_expires_at",
        table_name="cache_entries",
        postgresql_where="expires_at IS NOT NULL",
    )
    op.drop_table("cache_entries")
    op.drop_index(
        op.f("ix_annotation_sources_id"),
        table_name="annotation_sources",
    )
    op.drop_table("annotation_sources")

    # -- Drop ENUMs --
    op.execute("DROP TYPE IF EXISTS backup_trigger")
    op.execute("DROP TYPE IF EXISTS backup_status")
    op.execute("DROP TYPE IF EXISTS setting_category")
    op.execute("DROP TYPE IF EXISTS setting_type")
    op.execute("DROP TYPE IF EXISTS source_status")
