"""Initial schema

Revision ID: 2b9ab9b60926
Revises:
Create Date: 2025-08-16 08:06:18.554116

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b9ab9b60926"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hgnc_id", sa.String(length=50), nullable=True),
        sa.Column("approved_symbol", sa.String(length=100), nullable=False),
        sa.Column("aliases", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genes_approved_symbol"), "genes", ["approved_symbol"], unique=False)
    op.create_index(op.f("ix_genes_hgnc_id"), "genes", ["hgnc_id"], unique=True)
    op.create_index(op.f("ix_genes_id"), "genes", ["id"], unique=False)
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_runs_id"), "pipeline_runs", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "gene_curations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gene_id", sa.Integer(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=True),
        sa.Column("source_count", sa.Integer(), nullable=True),
        sa.Column("panelapp_panels", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("literature_refs", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("diagnostic_panels", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("hpo_terms", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("pubtator_pmids", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("omim_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("clinvar_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("constraint_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expression_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_score", sa.Float(), nullable=True),
        sa.Column("classification", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gene_id"),
    )
    op.create_index(
        op.f("ix_gene_curations_evidence_score"), "gene_curations", ["evidence_score"], unique=False
    )
    op.create_index(op.f("ix_gene_curations_id"), "gene_curations", ["id"], unique=False)
    op.create_table(
        "gene_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gene_id", sa.Integer(), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("source_detail", sa.String(length=255), nullable=True),
        sa.Column("evidence_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["gene_id"], ["genes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "gene_id", "source_name", "source_detail", name="gene_evidence_source_idx"
        ),
    )
    op.create_index(op.f("ix_gene_evidence_id"), "gene_evidence", ["id"], unique=False)
    op.create_index(
        op.f("ix_gene_evidence_source_name"), "gene_evidence", ["source_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gene_evidence_source_name"), table_name="gene_evidence")
    op.drop_index(op.f("ix_gene_evidence_id"), table_name="gene_evidence")
    op.drop_table("gene_evidence")
    op.drop_index(op.f("ix_gene_curations_id"), table_name="gene_curations")
    op.drop_index(op.f("ix_gene_curations_evidence_score"), table_name="gene_curations")
    op.drop_table("gene_curations")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_pipeline_runs_id"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index(op.f("ix_genes_id"), table_name="genes")
    op.drop_index(op.f("ix_genes_hgnc_id"), table_name="genes")
    op.drop_index(op.f("ix_genes_approved_symbol"), table_name="genes")
    op.drop_table("genes")
    # ### end Alembic commands ###
