"""Add gene normalization staging tables

Revision ID: 65d25f57857a
Revises: 1455a03d0cce
Create Date: 2025-08-16 16:35:24.390805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d25f57857a'
down_revision: Union[str, Sequence[str], None] = '1455a03d0cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_gene_evidence_gene_id_source'), table_name='gene_evidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_gene_evidence_gene_id_source'), 'gene_evidence', ['gene_id', 'source_name'], unique=False)
    # ### end Alembic commands ###
