"""Initial schema with users, genes, evidence, and curations

Revision ID: dfb64087cb58
Revises: 
Create Date: 2025-08-15 23:48:53.100504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfb64087cb58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene_curations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('gene_curations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('gene_curations', 'gene_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gene_curations', 'evidence_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_curations_gene'), table_name='gene_curations')
    op.drop_index(op.f('idx_curations_score'), table_name='gene_curations')
    op.create_index(op.f('ix_gene_curations_evidence_score'), 'gene_curations', ['evidence_score'], unique=False)
    op.create_index(op.f('ix_gene_curations_id'), 'gene_curations', ['id'], unique=False)
    op.drop_column('gene_curations', 'last_updated')
    op.add_column('gene_evidence', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('gene_evidence', 'gene_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gene_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_evidence_data'), table_name='gene_evidence', postgresql_using='gin')
    op.drop_index(op.f('idx_evidence_gene'), table_name='gene_evidence')
    op.drop_index(op.f('idx_evidence_source'), table_name='gene_evidence')
    op.create_index(op.f('ix_gene_evidence_id'), 'gene_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_gene_evidence_source_name'), 'gene_evidence', ['source_name'], unique=False)
    op.alter_column('genes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('genes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('genes_hgnc_id_key'), 'genes', type_='unique')
    op.drop_index(op.f('idx_genes_hgnc'), table_name='genes')
    op.drop_index(op.f('idx_genes_symbol'), table_name='genes')
    op.create_index(op.f('ix_genes_approved_symbol'), 'genes', ['approved_symbol'], unique=False)
    op.create_index(op.f('ix_genes_hgnc_id'), 'genes', ['hgnc_id'], unique=True)
    op.create_index(op.f('ix_genes_id'), 'genes', ['id'], unique=False)
    op.add_column('pipeline_runs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pipeline_runs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('pipeline_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.alter_column('pipeline_runs', 'completed_at',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('pipeline_runs', 'started_at',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('pipeline_runs', 'updated_at')
    op.drop_column('pipeline_runs', 'created_at')
    op.drop_index(op.f('ix_genes_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_hgnc_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_approved_symbol'), table_name='genes')
    op.create_index(op.f('idx_genes_symbol'), 'genes', ['approved_symbol'], unique=False)
    op.create_index(op.f('idx_genes_hgnc'), 'genes', ['hgnc_id'], unique=False)
    op.create_unique_constraint(op.f('genes_hgnc_id_key'), 'genes', ['hgnc_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('genes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('genes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_gene_evidence_source_name'), table_name='gene_evidence')
    op.drop_index(op.f('ix_gene_evidence_id'), table_name='gene_evidence')
    op.create_index(op.f('idx_evidence_source'), 'gene_evidence', ['source_name'], unique=False)
    op.create_index(op.f('idx_evidence_gene'), 'gene_evidence', ['gene_id'], unique=False)
    op.create_index(op.f('idx_evidence_data'), 'gene_evidence', ['evidence_data'], unique=False, postgresql_using='gin')
    op.alter_column('gene_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('gene_evidence', 'gene_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('gene_evidence', 'updated_at')
    op.add_column('gene_curations', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_gene_curations_id'), table_name='gene_curations')
    op.drop_index(op.f('ix_gene_curations_evidence_score'), table_name='gene_curations')
    op.create_index(op.f('idx_curations_score'), 'gene_curations', [sa.literal_column('evidence_score DESC')], unique=False)
    op.create_index(op.f('idx_curations_gene'), 'gene_curations', ['gene_id'], unique=False)
    op.alter_column('gene_curations', 'evidence_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('gene_curations', 'gene_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('gene_curations', 'updated_at')
    op.drop_column('gene_curations', 'created_at')
    # ### end Alembic commands ###
