# GENERATED by scripts/gen_contract.py — do not hand-edit
"""Exposed read-only API path-template constants.

GENERATED FILE — do not hand-edit.
Regenerate with ``scripts/gen_contract.py`` (``make contract``) from
``contract/openapi.snapshot.json``.
"""

from __future__ import annotations


GENES = "/api/genes/"
GENES_RESOLVE = "/api/genes/resolve"  # Wave 1b — not yet in OpenAPI snapshot
GENES_BY_GENE_SYMBOL = "/api/genes/{gene_symbol}"
GENES_BY_GENE_SYMBOL_EVIDENCE = "/api/genes/{gene_symbol}/evidence"
ANNOTATIONS_GENES_BY_GENE_ID_ANNOTATIONS = (
    "/api/annotations/genes/{gene_id}/annotations"
)
ANNOTATIONS_GENES_BY_GENE_ID_ANNOTATIONS_SUMMARY = (
    "/api/annotations/genes/{gene_id}/annotations/summary"
)
ANNOTATIONS_SOURCES = "/api/annotations/sources"
STATISTICS_SUMMARY = "/api/statistics/summary"
DATASOURCES = "/api/datasources/"
RELEASES = "/api/releases/"

ALL_PATHS: tuple[str, ...] = (
    GENES,
    GENES_RESOLVE,
    GENES_BY_GENE_SYMBOL,
    GENES_BY_GENE_SYMBOL_EVIDENCE,
    ANNOTATIONS_GENES_BY_GENE_ID_ANNOTATIONS,
    ANNOTATIONS_GENES_BY_GENE_ID_ANNOTATIONS_SUMMARY,
    ANNOTATIONS_SOURCES,
    STATISTICS_SUMMARY,
    DATASOURCES,
    RELEASES,
)
