# GENERATED by scripts/gen_contract.py — do not hand-edit
"""Gene filter / sort vocabularies + source name lists.

GENERATED FILE — do not hand-edit.
Regenerate with ``scripts/gen_contract.py`` (``make contract``) from
``contract/openapi.snapshot.json``.
"""

from __future__ import annotations


from typing import Literal

# --- gene filter / sort vocabularies (from OpenAPI) ---

EvidenceTier = Literal[
    "comprehensive_support",
    "multi_source_support",
    "established_support",
    "preliminary_evidence",
    "minimal_evidence",
]
EVIDENCE_TIER_VALUES: tuple[str, ...] = (
    "comprehensive_support",
    "multi_source_support",
    "established_support",
    "preliminary_evidence",
    "minimal_evidence",
)

EvidenceGroup = Literal["well_supported", "emerging_evidence"]
EVIDENCE_GROUP_VALUES: tuple[str, ...] = ("well_supported", "emerging_evidence")

GeneSortField = Literal[
    "id",
    "symbol",
    "approved_symbol",
    "hgnc_id",
    "score",
    "evidence_score",
    "count",
    "evidence_count",
    "created_at",
    "updated_at",
    "evidence_tier",
    "evidence_group",
]
GENE_SORT_FIELD_VALUES: tuple[str, ...] = (
    "id",
    "symbol",
    "approved_symbol",
    "hgnc_id",
    "score",
    "evidence_score",
    "count",
    "evidence_count",
    "created_at",
    "updated_at",
    "evidence_tier",
    "evidence_group",
)

# --- source name lists (hard-coded from design spec §4) ---

# 7 scored evidence sources (kgdb_get_gene_evidence)
EvidenceSource = Literal[
    "PanelApp", "HPO", "ClinGen", "GenCC", "PubTator", "DiagnosticPanels", "Literature"
]
EVIDENCE_SOURCE_VALUES: tuple[str, ...] = (
    "PanelApp",
    "HPO",
    "ClinGen",
    "GenCC",
    "PubTator",
    "DiagnosticPanels",
    "Literature",
)

# 10 descriptive annotation sources (kgdb_get_gene_annotations)
AnnotationSource = Literal[
    "hgnc",
    "gnomad",
    "clinvar",
    "ensembl",
    "uniprot",
    "gtex",
    "mpo_mgi",
    "string_ppi",
    "descartes",
    "hpo",
]
ANNOTATION_SOURCE_VALUES: tuple[str, ...] = (
    "hgnc",
    "gnomad",
    "clinvar",
    "ensembl",
    "uniprot",
    "gtex",
    "mpo_mgi",
    "string_ppi",
    "descartes",
    "hpo",
)
