# GENERATED by scripts/gen_contract.py — do not hand-edit
# generated by datamodel-codegen:
#   filename:  openapi.snapshot.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, RootModel, SecretStr


class BackupStatus(
    RootModel[Literal["pending", "running", "completed", "failed", "restored"]]
):
    root: Annotated[
        Literal["pending", "running", "completed", "failed", "restored"],
        Field(description="Backup job status enum", title="BackupStatus"),
    ]


class GrantType(RootModel[str]):
    root: Annotated[str, Field(pattern="^password$", title="Grant Type")]


class BodyLoginApiAuthLoginPost(BaseModel):
    client_id: Annotated[str | None, Field(title="Client Id")] = None
    client_secret: Annotated[SecretStr | None, Field(title="Client Secret")] = None
    grant_type: Annotated[GrantType | None, Field(title="Grant Type")] = None
    password: Annotated[SecretStr, Field(title="Password")]
    scope: Annotated[str | None, Field(title="Scope")] = ""
    username: Annotated[str, Field(title="Username")]


class BodyUploadEvidenceFileApiIngestionSourceNameUploadPost(BaseModel):
    file: Annotated[
        str,
        Field(
            json_schema_extra={"contentMediaType": "application/octet-stream"},
            title="File",
        ),
    ]
    mode: Annotated[str | None, Field(title="Mode")] = "merge"
    provider_name: Annotated[str | None, Field(title="Provider Name")] = None


class CacheClearResponse(BaseModel):
    entries_cleared: Annotated[int, Field(ge=0, title="Entries Cleared")]
    message: Annotated[str, Field(title="Message")]
    namespace: Annotated[str | None, Field(title="Namespace")] = None
    success: Annotated[bool, Field(title="Success")]


class CacheHealthResponse(BaseModel):
    cache_enabled: Annotated[bool, Field(title="Cache Enabled")]
    database_connected: Annotated[bool, Field(title="Database Connected")]
    http_cache_size_mb: Annotated[float, Field(ge=0.0, title="Http Cache Size Mb")]
    issues: Annotated[list[str] | None, Field(title="Issues")] = None
    last_cleanup: Annotated[AwareDatetime | None, Field(title="Last Cleanup")] = None
    memory_cache_size: Annotated[int, Field(ge=0, title="Memory Cache Size")]
    namespaces: Annotated[list[str], Field(title="Namespaces")]
    status: Annotated[str, Field(description="Overall health status", title="Status")]


class CacheKeyListResponse(BaseModel):
    has_more: Annotated[bool, Field(title="Has More")]
    keys: Annotated[list[str], Field(title="Keys")]
    namespace: Annotated[str, Field(title="Namespace")]
    page: Annotated[int, Field(ge=1, title="Page")]
    page_size: Annotated[int, Field(ge=1, title="Page Size")]
    total_keys: Annotated[int, Field(ge=0, title="Total Keys")]


class CacheStatsResponse(BaseModel):
    db_entries: Annotated[
        int,
        Field(
            description="Number of entries in database cache", ge=0, title="Db Entries"
        ),
    ]
    hit_rate: Annotated[
        float, Field(description="Cache hit rate", ge=0.0, le=1.0, title="Hit Rate")
    ]
    hits: Annotated[int, Field(description="Cache hits", ge=0, title="Hits")]
    memory_entries: Annotated[
        int,
        Field(
            description="Number of entries in memory cache",
            ge=0,
            title="Memory Entries",
        ),
    ]
    misses: Annotated[int, Field(description="Cache misses", ge=0, title="Misses")]
    namespace: Annotated[str | None, Field(title="Namespace")] = None
    total_entries: Annotated[
        int,
        Field(description="Total number of cache entries", ge=0, title="Total Entries"),
    ]
    total_size_bytes: Annotated[
        int,
        Field(description="Total cache size in bytes", ge=0, title="Total Size Bytes"),
    ]
    total_size_mb: Annotated[
        float,
        Field(description="Total cache size in MB", ge=0.0, title="Total Size Mb"),
    ]


class CacheWarmRequest(BaseModel):
    force_refresh: Annotated[
        bool | None,
        Field(description="Force refresh of existing cache", title="Force Refresh"),
    ] = False
    priority: Annotated[
        str | None, Field(pattern="^(low|normal|high)$", title="Priority")
    ] = "normal"
    sources: Annotated[
        list[str], Field(description="Data sources to warm up", title="Sources")
    ]


class CacheWarmResponse(BaseModel):
    entries_created: Annotated[int, Field(ge=0, title="Entries Created")]
    message: Annotated[str, Field(title="Message")]
    sources_warmed: Annotated[list[str], Field(title="Sources Warmed")]
    success: Annotated[bool, Field(title="Success")]
    time_taken_seconds: Annotated[float, Field(ge=0.0, title="Time Taken Seconds")]


class ErrorMessage(RootModel[str]):
    root: Annotated[
        str, Field(description="Error message", max_length=2000, title="Error Message")
    ]


class ErrorType(RootModel[str]):
    root: Annotated[
        str, Field(description="Error class name", max_length=200, title="Error Type")
    ]


class StackTrace(RootModel[str]):
    root: Annotated[
        str,
        Field(description="Error stack trace", max_length=10000, title="Stack Trace"),
    ]


class Url(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Page URL where error occurred", max_length=2000, title="Url"
        ),
    ]


class UserAgent(RootModel[str]):
    root: Annotated[
        str, Field(description="Browser user agent", max_length=500, title="User Agent")
    ]


class ClientLogCreate(BaseModel):
    context: Annotated[
        dict[str, Any] | None,
        Field(description="Additional context (JSONB)", title="Context"),
    ] = None
    error_message: Annotated[
        ErrorMessage | None, Field(description="Error message", title="Error Message")
    ] = None
    error_type: Annotated[
        ErrorType | None, Field(description="Error class name", title="Error Type")
    ] = None
    level: Annotated[
        str,
        Field(
            description="Log level",
            pattern="^(DEBUG|INFO|WARN|ERROR|CRITICAL)$",
            title="Level",
        ),
    ]
    message: Annotated[
        str, Field(description="Log message", max_length=2000, title="Message")
    ]
    stack_trace: Annotated[
        StackTrace | None, Field(description="Error stack trace", title="Stack Trace")
    ] = None
    url: Annotated[
        Url | None, Field(description="Page URL where error occurred", title="Url")
    ] = None
    user_agent: Annotated[
        UserAgent | None, Field(description="Browser user agent", title="User Agent")
    ] = None


class ClientLogResponse(BaseModel):
    status: Annotated[str | None, Field(title="Status")] = "accepted"


class CreateBackupRequest(BaseModel):
    compression_level: Annotated[
        int | None,
        Field(
            description="Compression level (0-9)", ge=0, le=9, title="Compression Level"
        ),
    ] = 6
    description: Annotated[
        str | None,
        Field(description="Optional description for the backup", title="Description"),
    ] = ""
    include_cache: Annotated[
        bool | None, Field(description="Include cache tables", title="Include Cache")
    ] = False
    include_logs: Annotated[
        bool | None,
        Field(description="Include system log tables", title="Include Logs"),
    ] = False
    parallel_jobs: Annotated[
        int | None,
        Field(description="Number of parallel jobs", ge=1, le=8, title="Parallel Jobs"),
    ] = 2


class EnrichmentResult(BaseModel):
    background_count: Annotated[int | None, Field(title="Background Count")] = None
    cluster_size: Annotated[int, Field(title="Cluster Size")]
    enrichment_score: Annotated[float, Field(title="Enrichment Score")]
    fdr: Annotated[float, Field(title="Fdr")]
    gene_count: Annotated[int, Field(title="Gene Count")]
    genes: Annotated[list[str], Field(title="Genes")]
    odds_ratio: Annotated[float, Field(title="Odds Ratio")]
    p_value: Annotated[float, Field(title="P Value")]
    term_id: Annotated[str, Field(title="Term Id")]
    term_name: Annotated[str, Field(title="Term Name")]


class GOEnrichmentRequest(BaseModel):
    cluster_genes: Annotated[
        list[int],
        Field(
            description="Gene IDs in cluster",
            max_length=500,
            min_length=1,
            title="Cluster Genes",
        ),
    ]
    fdr_threshold: Annotated[
        float | None,
        Field(
            description="FDR significance threshold",
            gt=0.0,
            le=1.0,
            title="Fdr Threshold",
        ),
    ] = 0.05
    gene_set: Annotated[
        str | None, Field(description="GSEApy gene set name", title="Gene Set")
    ] = "GO_Biological_Process_2023"
    timeout_seconds: Annotated[
        int | None,
        Field(
            description="API timeout (30-300 seconds)",
            ge=30,
            le=300,
            title="Timeout Seconds",
        ),
    ] = 120


class GOEnrichmentResponse(BaseModel):
    cluster_size: Annotated[
        int, Field(description="Cluster gene count", title="Cluster Size")
    ]
    fdr_threshold: Annotated[float, Field(title="Fdr Threshold")]
    gene_set: Annotated[str, Field(description="Gene set used", title="Gene Set")]
    results: Annotated[list[EnrichmentResult], Field(title="Results")]
    total_terms: Annotated[
        int, Field(description="Total significant terms", title="Total Terms")
    ]


class GeneCreate(BaseModel):
    aliases: Annotated[list[str] | None, Field(title="Aliases")] = []
    approved_symbol: Annotated[str, Field(title="Approved Symbol")]
    hgnc_id: Annotated[str | None, Field(title="Hgnc Id")] = None


class GeneNormalizationLogResponse(BaseModel):
    api_calls_made: Annotated[int | None, Field(title="Api Calls Made")] = 0
    approved_symbol: Annotated[str | None, Field(title="Approved Symbol")] = None
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    hgnc_id: Annotated[str | None, Field(title="Hgnc Id")] = None
    id: Annotated[int, Field(title="Id")]
    normalization_log: Annotated[dict[str, Any], Field(title="Normalization Log")]
    original_text: Annotated[str, Field(title="Original Text")]
    processing_time_ms: Annotated[int | None, Field(title="Processing Time Ms")] = None
    source_name: Annotated[str, Field(title="Source Name")]
    success: Annotated[bool, Field(title="Success")]


class GeneNormalizationStagingResponse(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    id: Annotated[int, Field(title="Id")]
    manual_aliases: Annotated[list[str] | None, Field(title="Manual Aliases")] = None
    manual_approved_symbol: Annotated[
        str | None, Field(title="Manual Approved Symbol")
    ] = None
    manual_hgnc_id: Annotated[str | None, Field(title="Manual Hgnc Id")] = None
    normalization_log: Annotated[dict[str, Any], Field(title="Normalization Log")]
    original_data: Annotated[dict[str, Any] | None, Field(title="Original Data")] = None
    original_text: Annotated[str, Field(title="Original Text")]
    priority_score: Annotated[int, Field(title="Priority Score")]
    requires_expert_review: Annotated[bool, Field(title="Requires Expert Review")]
    review_notes: Annotated[str | None, Field(title="Review Notes")] = None
    reviewed_at: Annotated[AwareDatetime | None, Field(title="Reviewed At")] = None
    reviewed_by: Annotated[str | None, Field(title="Reviewed By")] = None
    source_name: Annotated[str, Field(title="Source Name")]
    status: Annotated[str, Field(title="Status")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class HPOClassificationData(BaseModel):
    clinical_group: Annotated[
        str | None,
        Field(description="Clinical classification group", title="Clinical Group"),
    ] = None
    gene_id: Annotated[int, Field(description="Gene ID", title="Gene Id")]
    gene_symbol: Annotated[str, Field(description="Gene symbol", title="Gene Symbol")]
    is_syndromic: Annotated[
        bool | None, Field(description="Syndromic assessment", title="Is Syndromic")
    ] = False
    onset_group: Annotated[
        str | None, Field(description="Age of onset group", title="Onset Group")
    ] = None


class HPOClassificationRequest(BaseModel):
    gene_ids: Annotated[
        list[int],
        Field(
            description="List of gene IDs to fetch HPO classifications for",
            max_length=1000,
            min_length=1,
            title="Gene Ids",
        ),
    ]


class HPOClassificationResponse(BaseModel):
    data: Annotated[
        list[HPOClassificationData],
        Field(description="HPO classification data", title="Data"),
    ]
    metadata: Annotated[
        dict[str, Any], Field(description="Response metadata", title="Metadata")
    ]


class HPOEnrichmentRequest(BaseModel):
    background_genes: Annotated[
        list[int] | None,
        Field(
            description="Background gene set (default: all genes)",
            title="Background Genes",
        ),
    ] = None
    cluster_genes: Annotated[
        list[int],
        Field(
            description="Gene IDs in cluster to test",
            max_length=500,
            min_length=1,
            title="Cluster Genes",
        ),
    ]
    fdr_threshold: Annotated[
        float | None,
        Field(
            description="FDR significance threshold",
            gt=0.0,
            le=1.0,
            title="Fdr Threshold",
        ),
    ] = 0.05


class HPOEnrichmentResponse(BaseModel):
    cluster_size: Annotated[
        int, Field(description="Cluster gene count", title="Cluster Size")
    ]
    fdr_threshold: Annotated[float, Field(title="Fdr Threshold")]
    results: Annotated[list[EnrichmentResult], Field(title="Results")]
    total_terms: Annotated[
        int, Field(description="Total significant terms", title="Total Terms")
    ]


class NamespaceStatsResponse(BaseModel):
    active_entries: Annotated[
        int, Field(description="Non-expired entries", ge=0, title="Active Entries")
    ]
    avg_accesses: Annotated[float, Field(ge=0.0, title="Avg Accesses")]
    expired_entries: Annotated[
        int, Field(description="Expired entries", ge=0, title="Expired Entries")
    ]
    last_access_time: Annotated[
        AwareDatetime | None, Field(title="Last Access Time")
    ] = None
    namespace: Annotated[str, Field(title="Namespace")]
    newest_entry: Annotated[AwareDatetime | None, Field(title="Newest Entry")] = None
    oldest_entry: Annotated[AwareDatetime | None, Field(title="Oldest Entry")] = None
    total_accesses: Annotated[int, Field(ge=0, title="Total Accesses")]
    total_entries: Annotated[int, Field(ge=0, title="Total Entries")]
    total_size_bytes: Annotated[int, Field(ge=0, title="Total Size Bytes")]


class NetworkBuildRequest(BaseModel):
    gene_ids: Annotated[
        list[int],
        Field(
            description="List of gene IDs to include in network",
            max_length=2000,
            min_length=1,
            title="Gene Ids",
        ),
    ]
    largest_component_only: Annotated[
        bool | None,
        Field(
            description="Keep only largest connected component",
            title="Largest Component Only",
        ),
    ] = False
    min_degree: Annotated[
        int | None,
        Field(
            description="Minimum node degree (0=include all, 1=remove isolated, 2+=require multiple interactions)",
            ge=0,
            le=10,
            title="Min Degree",
        ),
    ] = 0
    min_string_score: Annotated[
        int | None,
        Field(
            description="Minimum STRING confidence score (0-1000)",
            ge=0,
            le=1000,
            title="Min String Score",
        ),
    ] = 400
    remove_isolated: Annotated[
        bool | None,
        Field(
            description="Remove nodes with no interactions (degree=0)",
            title="Remove Isolated",
        ),
    ] = False


class NetworkBuildResponse(BaseModel):
    components: Annotated[
        int, Field(description="Number of connected components", title="Components")
    ]
    cytoscape_json: Annotated[
        dict[str, Any], Field(description="Cytoscape.js format", title="Cytoscape Json")
    ]
    edges: Annotated[int, Field(description="Number of edges", title="Edges")]
    nodes: Annotated[int, Field(description="Number of nodes", title="Nodes")]


class NetworkClusterRequest(BaseModel):
    algorithm: Annotated[
        str | None,
        Field(
            description="Clustering algorithm: leiden, louvain, or walktrap",
            title="Algorithm",
        ),
    ] = "leiden"
    gene_ids: Annotated[
        list[int],
        Field(
            description="List of gene IDs in network",
            max_length=2000,
            min_length=1,
            title="Gene Ids",
        ),
    ]
    largest_component_only: Annotated[
        bool | None,
        Field(
            description="Keep only largest connected component",
            title="Largest Component Only",
        ),
    ] = False
    min_cluster_size: Annotated[
        int | None,
        Field(
            description="Minimum cluster size (1=keep all, 3+=filter small clusters)",
            ge=1,
            le=50,
            title="Min Cluster Size",
        ),
    ] = 1
    min_degree: Annotated[
        int | None,
        Field(
            description="Minimum node degree filter", ge=0, le=10, title="Min Degree"
        ),
    ] = 0
    min_string_score: Annotated[
        int | None,
        Field(
            description="Minimum STRING confidence score (0-1000)",
            ge=0,
            le=1000,
            title="Min String Score",
        ),
    ] = 400
    remove_isolated: Annotated[
        bool | None,
        Field(description="Remove isolated nodes (degree=0)", title="Remove Isolated"),
    ] = False


class NetworkClusterResponse(BaseModel):
    algorithm: Annotated[str, Field(description="Algorithm used", title="Algorithm")]
    clusters: Annotated[
        dict[str, int],
        Field(description="Gene ID -> cluster ID mapping", title="Clusters"),
    ]
    components: Annotated[
        int, Field(description="Number of connected components", title="Components")
    ]
    cytoscape_json: Annotated[
        dict[str, Any],
        Field(description="Cytoscape.js with cluster colors", title="Cytoscape Json"),
    ]
    edges: Annotated[
        int, Field(description="Number of edges in clustered network", title="Edges")
    ]
    modularity: Annotated[
        float, Field(description="Modularity score", title="Modularity")
    ]
    nodes: Annotated[
        int, Field(description="Number of nodes in clustered network", title="Nodes")
    ]
    num_clusters: Annotated[
        int, Field(description="Number of clusters detected", title="Num Clusters")
    ]


class NormalizationStatsResponse(BaseModel):
    by_source: Annotated[dict[str, dict[str, Any]], Field(title="By Source")]
    success_rate: Annotated[float, Field(title="Success Rate")]
    successful_attempts: Annotated[int, Field(title="Successful Attempts")]
    total_attempts: Annotated[int, Field(title="Total Attempts")]


class PasswordChange(BaseModel):
    current_password: Annotated[str, Field(title="Current Password")]
    new_password: Annotated[str, Field(min_length=8, title="New Password")]


class PasswordReset(BaseModel):
    email: Annotated[EmailStr, Field(title="Email")]


class PasswordResetConfirm(BaseModel):
    new_password: Annotated[str, Field(min_length=8, title="New Password")]
    token: Annotated[str, Field(title="Token")]


class ReleaseResponse(BaseModel):
    citation_text: Annotated[str | None, Field(title="Citation Text")] = None
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    doi: Annotated[str | None, Field(title="Doi")] = None
    export_checksum: Annotated[str | None, Field(title="Export Checksum")] = None
    export_file_path: Annotated[str | None, Field(title="Export File Path")] = None
    gene_count: Annotated[int | None, Field(title="Gene Count")] = None
    id: Annotated[int, Field(title="Id")]
    published_at: Annotated[AwareDatetime | None, Field(title="Published At")] = None
    published_by_id: Annotated[int | None, Field(title="Published By Id")] = None
    release_date: Annotated[AwareDatetime | None, Field(title="Release Date")] = None
    release_notes: Annotated[
        str | None, Field(description="Optional release notes", title="Release Notes")
    ] = None
    status: Annotated[str, Field(title="Status")]
    total_evidence_count: Annotated[int | None, Field(title="Total Evidence Count")] = (
        None
    )
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    version: Annotated[
        str, Field(description="CalVer version (e.g., 2025.10)", title="Version")
    ]


class ReleaseUpdate(BaseModel):
    release_notes: Annotated[
        str | None, Field(description="Optional release notes", title="Release Notes")
    ] = None
    version: Annotated[
        str | None, Field(description="CalVer version (e.g., 2025.10)", title="Version")
    ] = None


class RestoreBackupRequest(BaseModel):
    create_safety_backup: Annotated[
        bool | None,
        Field(
            description="Create safety backup before restore",
            title="Create Safety Backup",
        ),
    ] = True
    drop_existing: Annotated[
        bool | None, Field(description="Drop existing database", title="Drop Existing")
    ] = True
    run_analyze: Annotated[
        bool | None, Field(description="Run ANALYZE after restore", title="Run Analyze")
    ] = True


class SettingCategory(
    RootModel[
        Literal[
            "cache",
            "security",
            "pipeline",
            "api",
            "database",
            "backup",
            "logging",
            "features",
        ]
    ]
):
    root: Annotated[
        Literal[
            "cache",
            "security",
            "pipeline",
            "api",
            "database",
            "backup",
            "logging",
            "features",
        ],
        Field(description="Setting category enum", title="SettingCategory"),
    ]


class StagingApprovalRequest(BaseModel):
    aliases: Annotated[
        list[str] | None, Field(description="Gene aliases", title="Aliases")
    ] = None
    approved_symbol: Annotated[
        str,
        Field(description="Manually corrected gene symbol", title="Approved Symbol"),
    ]
    hgnc_id: Annotated[str, Field(description="HGNC ID for the gene", title="Hgnc Id")]
    notes: Annotated[str | None, Field(description="Review notes", title="Notes")] = (
        None
    )
    reviewer: Annotated[
        str | None, Field(description="Name of reviewer", title="Reviewer")
    ] = "system"


class StagingRejectionRequest(BaseModel):
    notes: Annotated[
        str | None, Field(description="Rejection reason", title="Notes")
    ] = None
    reviewer: Annotated[
        str | None, Field(description="Name of reviewer", title="Reviewer")
    ] = "system"


class StagingStatsResponse(BaseModel):
    by_source: Annotated[dict[str, int], Field(title="By Source")]
    total_approved: Annotated[int, Field(title="Total Approved")]
    total_pending: Annotated[int, Field(title="Total Pending")]
    total_rejected: Annotated[int, Field(title="Total Rejected")]


class SubgraphRequest(BaseModel):
    gene_ids: Annotated[
        list[int],
        Field(
            description="Full network gene IDs",
            max_length=2000,
            min_length=1,
            title="Gene Ids",
        ),
    ]
    k: Annotated[
        int | None, Field(description="Number of hops (1-5)", ge=1, le=5, title="K")
    ] = 2
    min_string_score: Annotated[
        int | None,
        Field(
            description="Minimum STRING confidence score",
            ge=0,
            le=1000,
            title="Min String Score",
        ),
    ] = 400
    seed_gene_ids: Annotated[
        list[int],
        Field(
            description="Seed gene IDs to center subgraph around",
            max_length=50,
            min_length=1,
            title="Seed Gene Ids",
        ),
    ]


class Token(BaseModel):
    access_token: Annotated[str, Field(title="Access Token")]
    expires_in: Annotated[
        int, Field(description="Token expiration time in seconds", title="Expires In")
    ]
    refresh_token: Annotated[str | None, Field(title="Refresh Token")] = None
    token_type: Annotated[str | None, Field(title="Token Type")] = "bearer"


class UpdateSettingRequest(BaseModel):
    change_reason: Annotated[
        str | None,
        Field(description="Optional reason for change", title="Change Reason"),
    ] = None
    value: Annotated[Any, Field(description="New value for the setting", title="Value")]


class FullName(RootModel[str]):
    root: Annotated[str, Field(max_length=255, title="Full Name")]


class UserRegister(BaseModel):
    email: Annotated[EmailStr, Field(title="Email")]
    full_name: Annotated[FullName | None, Field(title="Full Name")] = None
    password: Annotated[str, Field(min_length=8, title="Password")]
    role: Annotated[
        str | None, Field(pattern="^(admin|curator|viewer)$", title="Role")
    ] = "viewer"
    username: Annotated[
        str,
        Field(
            max_length=50, min_length=3, pattern="^[a-zA-Z0-9_-]+$", title="Username"
        ),
    ]


class UserResponse(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    email: Annotated[str, Field(title="Email")]
    full_name: Annotated[str | None, Field(title="Full Name")] = None
    id: Annotated[int, Field(title="Id")]
    is_active: Annotated[bool, Field(title="Is Active")]
    is_verified: Annotated[bool, Field(title="Is Verified")]
    last_login: Annotated[AwareDatetime | None, Field(title="Last Login")] = None
    permissions: Annotated[list[str], Field(title="Permissions")]
    role: Annotated[str, Field(title="Role")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    username: Annotated[str, Field(title="Username")]


class Role(RootModel[str]):
    root: Annotated[str, Field(pattern="^(admin|curator|viewer)$", title="Role")]


class UserUpdate(BaseModel):
    email: Annotated[EmailStr | None, Field(title="Email")] = None
    full_name: Annotated[FullName | None, Field(title="Full Name")] = None
    is_active: Annotated[bool | None, Field(title="Is Active")] = None
    is_verified: Annotated[bool | None, Field(title="Is Verified")] = None
    role: Annotated[Role | None, Field(title="Role")] = None


class ValidationError(BaseModel):
    ctx: Annotated[dict[str, Any] | None, Field(title="Context")] = None
    input: Annotated[Any | None, Field(title="Input")] = None
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class ReleaseList(BaseModel):
    data: Annotated[list[ReleaseResponse], Field(title="Data")]
    meta: Annotated[dict[str, int], Field(title="Meta")]
